### PR TITLE
Use npm@6.11 in CircleCI config to fix broken build from git dependencies

### LINKED ISSUE #221: Use phovea_clue@develop in tdp_core develop branch
* Release number or git hash: b005fb75997b3ffc104e621ce6a8593d5c241782
* Environment (local or deployed): both

### Observed behavior

Currently the development build is referencing a specific version of phovea_clue

https://github.com/datavisyn/tdp_core/blob/b005fb75997b3ffc104e621ce6a8593d5c241782/package.json#L82

That causes problems in some dependent CircleCI builds (e.g., https://github.com/Caleydo/ordino/pull/208), where some bugfixes and features from phovea_clue and phovea_core are not available.

### Expected behavior

* Use the develop branch of phovea_clue in tdp_core develop branch

### PR DESCRIPTION
**Pull request by thinkh**
Fixes #221.

Related PR https://github.com/datavisyn/dTiles/pull/210

### Summary

* Switch phovea_clue to develop branch
* Installs npm@6.11 during CircleCI build to fix dependency problems
  * Probably fixed in [v6.6.0](https://github.com/npm/cli/releases/tag/v6.6.0) with https://github.com/npm/cli/pull/123
* Improved build step names
* Show installed npm dependencies

### Next steps

* Our [Docker build image](https://github.com/phovea/phovea_circleci_python/blob/b2f8dabdd57753deb17646b23f1223a9b9a6e47b/Dockerfile#L9) `caleydo/phovea_circleci_python:v2.0` installs `node 8.x`, which resolves to node@8.14.0 and npm@6.4.1
  * Side note: [we defined node@8.16.1](https://wiki.datavisyn.io/internal/developer/software-requirements#development), which (sadly) also resolves to npm@6.4.1 (see https://nodejs.org/en/download/releases/)
  * Hence, we must install npm@6.11 manually for CircleCI and our local dev environment, which requires an update of the Wiki documentation and the generator-phovea
* Instead of installing npm@6.11 with every CircleCI build we should rather install the version directly in our Docker build image and release it as `caleydo/phovea_circleci_python:v3.0`
* Afterwards we must update all our CircleCI configs to `caleydo/phovea_circleci_python:v3.0`

### CODE REVIEW

**Comment by thinkh** [comment]
@lehnerchristian and @dg-datavisyn Could you please run `node -v` `npm -v` and post your local versions here for comparison?  I'd like to compare the versions, because I'm still wondering why usually locally everything works well, but it results in CircleCI build errors.

**Comment by lehnerchristian** [comment]
I use node@8.15.0 and npm@6.4.1

**Comment by lehnerchristian** [comment]
but I'll update npm locally

**Comment by thinkh** [comment]
After testing the different npm versions it seems that [npm@6.6.0](https://github.com/npm/cli/releases/tag/v6.6.0) is working. Looking at the release notes it might be that https://github.com/npm/cli/pull/123/files fixes the handling of git branches in dependent package.json.

**Comment by thinkh** [comment]
Following the release notes [npm@6.9.0](https://github.com/npm/cli/releases/tag/v6.9.0) solves [git dependencies with #semver: don’t seem to resolve and dedup correctly](https://github.com/npm/cli/pull/115), which might be relevant for us since we are using semver ranges in for git branches.

**Comment by thinkh** [comment]
We (@anita-steiner, @dg-datavisyn, and @lehnerchristian) agreed in a personal meeting that we will test and update to Node 12 LTS (see https://github.com/phovea/generator-phovea/issues/191), which includes npm@6.11.

**Comment by thinkh** [comment]
The next generator release uses Node.js v12. After updating the CircleCI config to the new version, we this issue should be fixed.

**Comment by thinkh** [comment]
Close this PR and open a new (clean) PR instead.

**Pull request closed without merging**
