### PR TITLE
Added lazy loaded column interface to functions like addLazyColu…

### PR DESCRIPTION
**Pull request by dvmichaelpuehringer**
Moved the inline-return-value-definition of `addLazyColumn` to a separate interface which is now used as return-value for functions such as `addTrackedScoreColumn` to improve type safety.

### CODE REVIEW

**Comment by thinkh** [comment]
@lehnerchristian What the status here?

**Comment by thinkh** [comment]
@lehnerchristian Would you tag this PR as **minor**, because a new TS interface was added, or as **patch**, because nothing has changed to the outside?

**Comment by dvmichaelpuehringer** [comment]
@thinkh the interface is just extracted from the existing return value for reusability, it does not really change anything (internally/externally) as it was inferable by TS before as well.

**Comment by lehnerchristian** [comment]
I've tested it yesterday in two apps and it worked for me --> at least I had no compiler errors

However I don't have some apps installed, so I cannot test them there

**Comment by lehnerchristian** [comment]
I'd say it's a patch, isn't it?

**Comment by thinkh** [comment]
Yes, let's label it as patch. Anyway there will be a major release next time. 😉

**Pull request merged**
