### PR TITLE
fix: migrate local to remote graph without intermediate requests

### PR DESCRIPTION
**Pull request by thinkh**
Closes https://github.com/Caleydo/tdp_bi_bioinfodb/issues/1443

### Developer Checklist (Definition of Done)

**Issue**

- [x] All acceptance criteria from the issue are met
- [x] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [ ] Requires UI/UX/Vis review
  - [ ] Reviewer(s) are notified (_tag assignees_)
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [x] Branch is up-to-date with the branch to be merged with, i.e., develop
- [x] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [x] Descriptive title for this pull request is provided (will be used for release notes later)
- [x] Reviewer and assignees are defined
- [x] Add type label (e.g., *bug*, *feature*) to this pull request
- [x] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [x] The PR is connected to the corresponding issue (via `Closes #...`)
- [x] [Summary of changes](#summary-of-changes) is written

### Summary of changes

Previously migrating a local provenance graph ("Temporary session") to a remote storage graph ("Saved session") required three requests:

1. POST `/api/dataset/` with graph metadata as payload to save graph metadata
2. GET `/api/dataset/graph/test4Jvs0Q/data` which returns the empty graph --> this where the empty graph gets cached that causes the problems down the road
3. POST `/api/dataset/test4Jvs0Q` with session data as payload to save the graph data

The problem is that the second one with the empty graph was cached by the browser and Ordino thought it has to initialize a new graph for the given saved session. The additional states were appended to the already existing saved session and caused an invalid graph.

This PR refactors the code and removes the second and third request by sending the graph data as part of the first request. The remote storage graph is then created from the returned metadata (which contains the graph id). After that all future graph updates (states/actions) are synced to the server and the graph data is persisted in the MongoDB.

grafik

In a local workspace the flow looks like this now:

[ordino-migrate-to-remote-graph-fixed.webm](https://github.com/Caleydo/tdp_bi_bioinfodb/assets/5851088/4c005f8e-91a6-4f5b-a254-81042c0ba727)

### Additional notes for the reviewer(s)

- @puehringer I'm not sure if you use the feature to migrate local graphs to remote graphs in your apps. If yes, please give it a test if everything still works.

---
Thanks for creating this pull request 🤗

### CODE REVIEW

**Review by oltionchampari — CHANGES_REQUESTED** [review]
Thanks for the well documented PR. The original issue is fixed. 
One thing that does not work anymore though is importing an exported session that has been previously saved.
This works in the public version.

gr

**Comment by thinkh** [comment]
@oltionchampari Thanks for your review and pointing out the bug. I fixed the bug with my last commit where I pass the nodes and edges to the remote store graph (instead of loading it from the server as done previously). Please give it one more try. Thanks.


[ordino-migrate-to-remote-graph-fixed.webm](https://github.com/datavisyn/tdp_core/assets/5851088/7be20b20-8cc4-4933-8ae7-86da2ffef868)

**Review by oltionchampari — APPROVED** [review]
Tested again the original bug and the exporting functionality, and they both work as expected.
Thanks

**Comment by thinkh** [comment]
@dvdanielamoitzi please test (or delegate) this PR with your apps that are using provenance tracking. Thanks.

**Comment by thinkh** [comment]
@puehringer and @dvmartinweigl tested this PR in their apps and it worked as expected for them.

**Pull request merged**
