### PR TITLE
Remember filter settings

### PR DESCRIPTION
**Pull request by lehnerchristian**
closes Caleydo/tdp_bi_bioinfodb#692

### CODE REVIEW

**Comment by lehnerchristian** [comment]
I found an issue with that. the session value needs to be reset when clicking on the `x` (close) button in a row. I'll fix it and comment again, when it's ready to review

**Comment by sgratzl** [comment]
isn't the main issue that the following method won't be called for FormMaps?

https://github.com/datavisyn/tdp_core/blob/0e43af866398906d4e89b4e8bd73304776fdb606/src/form/internal/AFormElement.ts#L75-L86

**Comment by lehnerchristian** [comment]
right, that's the issue

**Comment by sgratzl** [comment]
there was a reason why the super method wasn't called. Does it still work for both the inline and regular (=score) case?

**Comment by lehnerchristian** [comment]
yes, for me it's working. the filter settings are remembered, as the issue says, which is addressed by this issue. or was the reason that aggregated score dialogs should not remember the filters?
test

**Comment by sgratzl** [comment]
> yes, for me it's working. the filter settings are remembered, as the issue says, which is addressed by this issue. or was the reason that aggregated score dialogs should not remember the filters?

take a close look -> the filter label is twice since both the `super.build` and `build` adds it.

**Pull request merged**
