### PR TITLE
Sgratzl/lineupjs3.1

### PR DESCRIPTION
**Pull request by sgratzl**
updates to lineupjs3.1 

"should" also work with lineupjs3.0 (but not tested)

### CODE REVIEW

**Comment by sluger** [comment]
should this work with patentbay too or are there some adjustments to make before using lineupjs@3.1?

**Comment by lehnerchristian** [comment]
looks good in general, also the sidebar styling issue is resolved
however, as discussed yesterday, on my system I get scrollbars in most of the cells and there is the font rendering issue in score columns when the bar and the text overlap
peek 2018-08-01 08-47

**Comment by sgratzl** [comment]
what happens on https://lineup.js.org/app

**Comment by sgratzl** [comment]
and regarding the coloring bug -> https://github.com/datavisyn/lineupjs/issues/47

**Comment by lehnerchristian** [comment]
no scrollbars:

peek 2018-08-01 08-54

**Pull request merged**
