### PR TITLE
Refactor form builder to use inline form property and Bootstrap form layout

### LINKED ISSUE #531: Wrong spacing for checkboxes
In the current develop branch, the `FormCheckBox` receives a margin top spacing that is needed for normal forms but should not be visible in the case of inline forms.

### PR DESCRIPTION
**Pull request by dvvanessastoiber**
Closes #531 

### Summary

* Add property `inlineForm` to the options of `IFormElementDesc`
* Adapt typings for interfaces
* improve usage of spacing utilities (margins, cols and grids)

### CODE REVIEW

**Review by thinkh — CHANGES_REQUESTED** [review]
Unfortunately, this change breaks the paramter form in Ordino. All elements take now the full width and are not positioned next to each other as before.

**Before**

grafik


**After**

grafik


grafik


Please test in Ordino again and modify or revert the change again. Thanks.

**Comment by dvdanielrehberger** [comment]
This PR is fine for Bayer apps. I changed the status to ready for review.

**Review by thinkh — CHANGES_REQUESTED** [review]
@dvdanielrehberger Thanks for the changes. I tested it again and it works fine for dropdowns and buttons, but there is still a gap missing for checkbox for inline forms. Can you please check it again and fix it?

grafik

**Edit**

Moving the `col-sm-auto` to a separate div and nest the rest inside seems to work. Please test and provide a fix. Thanks.

grafik

**Comment by dvvanessastoiber** [comment]
I have committed some fixes for Ordino. @thinkh Please test it again and have a look at the following related PRs:
- https://github.com/Caleydo/tdp_gene/pull/158
-  https://github.com/Caleydo/ordino/pull/332
Thank you!

**Comment by dvvanessastoiber** [comment]
@puehringer I have tested the latest changes for the FormElements in Ordino and it works in my tests / looks good from my point of view. Thank you for the changes! :+1:

**Review by thinkh — APPROVED** [review]
I tested this branch together with the other branches from @dvvanessastoiber in Ordino and it looks good to me. 👍 From my side this PR is ready to be merged.

Thanks for the work and the refactoring!

**Pull request merged**
