### PR TITLE
Added extension point to manage database migrations

### PR DESCRIPTION
**Pull request by puehringer**
### Summary
This PR adds the ability to tightly integrate Alembic migrations into `tdp_core` applications. 

### How it works
On startup, the `DBMigrationManager` retrieves all extension points with the key `tdp-sql-database-migration` and creates a `DBMigration` object for each them. This procedure is very similar to how `DBConnector` are loaded. A `DBMigration` then can execute *all* Alembic commands (`upgrade`, `downgrade`, `history`, `stamp`, ...) with *all* options within the context of a specific migration.

### How to use
The documentation moved to https://wiki.datavisyn.io/tdp/extension-points/db-migration

### CODE REVIEW

**Comment by lehnerchristian** [comment]
After the demo yesterday I think we can merge. @thinkh you made some notes as far as I saw. do you want to copy them over?

**Comment by thinkh** [comment]
I did not take notes, since @puehringer rembembered the to dos.

@puehringer Your turn. 😉

**Comment by puehringer** [comment]
- [ ] Add possibility to configure schema where the `alembic_version` table is stored
- [ ] Check commands which require `-arg` (especially revision -m "...") 

@thinkh Of course I remembered everything :wink:

**Comment by puehringer** [comment]
@thinkh @lehnerchristian The two remaining issues are solved and documented in the wiki. This PR is therefore ready to merge.

**Comment by lehnerchristian** [comment]
one thing I noticed in the docs: in https://wiki.datavisyn.io/tdp/extension-points/db-migration#initializing-the-migrations-folder you're updating the access rights for the new migration folder

the command you use is `sudo chown $USER:$USER -R alembic alembic.ini`

however it should be `sudo chown $USER:$USER -R migration alembic.ini`, shouldn't it?

**Comment by puehringer** [comment]
@lehnerchristian I changed it to `sudo chown $USER:$USER -R migration`, as the `ini` is supplied by `tdp_core#dbmigration.ini`. Thanks for the hint!

**Pull request merged**
