### PR TITLE
allow to wait for the selection changes to be applied

### PR DESCRIPTION
**Pull request by sgratzl**
possible fix for that ranking changes cannot be applied while columns are still loading

### CODE REVIEW

**Comment by thinkh** [comment]
I get a compile error for views in tdp_public_db that extend `ARankingView`:

image

**Comment by sgratzl** [comment]
to late - already fixed

**Comment by thinkh** [comment]
Ok, I will try it again.

**Comment by thinkh** [comment]
I'm still getting an error, but I'm not sure if I tested it correctly.

1. Export the provenance graph from https://ordino.caleydoapp.org (see [Ordino Paper Case Study 1.json.txt](https://github.com/datavisyn/tdp_core/files/1737194/Ordino.Paper.Case.Study.1.json.txt))
2. Checkout this branch and and the https://github.com/Caleydo/ordino/pull/190 on my local machine
3. Import the provenance graph locally
4. It tries to run until the end, but stops again with the same error message

image

**Comment by thinkh** [comment]
Thanks for you latest changes. Now it works in my local environment.
I will accept merge the PR and start the deployment again.

**Comment by thinkh** [comment]
@sgratzl Will you file a PR for the changes in the `resolveImmediately` branch in phovea_clue as well (or merge it directly)?

**Comment by sgratzl** [comment]
> @sgratzl Will you file a PR for the changes in the resolveImmediately branch in phovea_clue as well (or merge it directly)?

yes, I just created them. Tho, I cannot promise ( ;) ) that other projects depending on the phovea_clue like StratomeX won't have compile errors

**Comment by thinkh** [comment]
Ok. We'll see the errors in other projects next build. ;-)

**Pull request merged**
