### PR TITLE
Change the text of `Security Information` and `openExternally` message for ProxyViews

### PR DESCRIPTION
**Pull request by oltionchampari**
Closes datavisyn/tdp_core#421

### Summary 

* Harmonized message for `Security Information` and `openExternally` notifications
* Removed unnecessary `<p>` wrapping the notification `div`
* Extracted the style information to `view_proxy` stylesheet

### Screenshot

grafik

### CODE REVIEW

**Review by thinkh — CHANGES_REQUESTED** [review]
@oltionchampari Thanks for the first part. Please update the open externally message, too (see https://github.com/datavisyn/tdp_core/issues/421#issuecomment-690984844).

**Comment by oltionchampari** [comment]
> @oltionchampari Thanks for the first part. Please update the open externally message, too (see [#421 (comment)](https://github.com/datavisyn/tdp_core/issues/421#issuecomment-690984844)).

Thanks, i misread the issue, and missed the second part.
The `MessagingRroxyView` has no open externally message implemented.

**Review by thinkh — APPROVED** [review]
Thanks. Looks good now. 👍

**Comment by thinkh** [comment]
@anita-steiner + @dg-datavisyn Please have a look, if the proxy message works for you, too? This message is shown when the `openExternally` flag is set in the phovea.ts or an HTTP view is opened from an HTTPS url.

grafik

**Comment by thinkh** [comment]
Feedback: works for both. Hence, I will continue and merge this PR.

**Pull request merged**
